import { EmptyState, PageHeader, SectionCard, arabicDate, money } from "@/components/accounting/ui";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CalendarClock, CirclePause, PackagePlus, Plus } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

type PackageForm = { name: string; description: string; durationDays: string; price: string; currencyCode: "YER" | "SAR" | "USD" };
type SubscriptionForm = { contactId: string; packageId: string; startDate: string; notes: string };
const blankPackage = (): PackageForm => ({ name: "", description: "", durationDays: "30", price: "", currencyCode: "YER" });
const blankSubscription = (): SubscriptionForm => ({ contactId: "", packageId: "", startDate: new Date().toISOString().slice(0, 10), notes: "" });
const statusLabels: Record<string, { label: string; className: string }> = { active: { label: "فعالة", className: "bg-[#eaf7f2] text-[#08735d]" }, expiring: { label: "قريبة الانتهاء", className: "bg-[#fff7df] text-[#9c711a]" }, expired: { label: "منتهية", className: "bg-[#fff1f2] text-[#b9404a]" }, suspended: { label: "موقوفة", className: "bg-slate-100 text-slate-600" } };

export default function SubscriptionsPage() {
  const packagesQuery = trpc.accounting.servicePackages.useQuery();
  const subscriptionsQuery = trpc.accounting.subscriptions.useQuery();
  const contactsQuery = trpc.accounting.contacts.useQuery();
  const utils = trpc.useUtils();
  const [packageOpen, setPackageOpen] = useState(false);
  const [subscriptionOpen, setSubscriptionOpen] = useState(false);
  const [packageForm, setPackageForm] = useState<PackageForm>(blankPackage());
  const [subscriptionForm, setSubscriptionForm] = useState<SubscriptionForm>(blankSubscription());
  const createPackage = trpc.accounting.createServicePackage.useMutation({ onSuccess: async () => { await utils.accounting.servicePackages.invalidate(); toast.success("تمت إضافة الباقة"); setPackageOpen(false); }, onError: error => toast.error(error.message) });
  const createSubscription = trpc.accounting.createSubscription.useMutation({ onSuccess: async () => { await Promise.all([utils.accounting.subscriptions.invalidate(), utils.accounting.dashboard.invalidate()]); toast.success("تم إنشاء اشتراك العميل"); setSubscriptionOpen(false); }, onError: error => toast.error(error.message) });
  const updateStatus = trpc.accounting.updateSubscriptionStatus.useMutation({ onSuccess: async () => { await utils.accounting.subscriptions.invalidate(); toast.success("تم تحديث حالة الاشتراك"); }, onError: error => toast.error(error.message) });
  function submitPackage(event: FormEvent) { event.preventDefault(); createPackage.mutate({ ...packageForm, durationDays: Number(packageForm.durationDays) }); }
  function submitSubscription(event: FormEvent) { event.preventDefault(); if (!subscriptionForm.contactId || !subscriptionForm.packageId) { toast.error("اختر العميل والباقـة أولاً"); return; } createSubscription.mutate({ contactId: Number(subscriptionForm.contactId), packageId: Number(subscriptionForm.packageId), startDate: new Date(`${subscriptionForm.startDate}T12:00:00`), notes: subscriptionForm.notes || undefined }); }
  const activePackages = (packagesQuery.data ?? []).filter(item => item.isActive);
  const customerContacts = (contactsQuery.data ?? []).filter(item => item.type === "customer" || item.type === "grocery");
  return <div><PageHeader title="الباقات والاشتراكات" description="أنشئ باقات الإنترنت ثم اربط كل عميل باشتراك مستقل. تتابع الحالة تلقائياً: فعالة، قريبة الانتهاء، منتهية، أو موقوفة." action={<div className="flex gap-2"><Button variant="outline" onClick={() => { setPackageForm(blankPackage()); setPackageOpen(true); }} className="h-11 border-[#bcd9d2] font-bold text-[#0a6372] hover:bg-[#eff8f5]"><PackagePlus className="ml-2 h-4 w-4" />إضافة باقة</Button><Button onClick={() => { setSubscriptionForm(blankSubscription()); setSubscriptionOpen(true); }} className="h-11 bg-[#0a6372] font-bold hover:bg-[#084e5a]"><Plus className="ml-2 h-4 w-4" />اشتراك جديد</Button></div>} />
    <Tabs defaultValue="subscriptions"><TabsList className="mb-5 h-auto rounded-xl bg-[#eaf3f1] p-1"><TabsTrigger value="subscriptions" className="rounded-lg px-5 py-2.5 data-[state=active]:bg-white data-[state=active]:text-[#0a6372]">اشتراكات العملاء</TabsTrigger><TabsTrigger value="packages" className="rounded-lg px-5 py-2.5 data-[state=active]:bg-white data-[state=active]:text-[#0a6372]">الباقات</TabsTrigger></TabsList>
      <TabsContent value="subscriptions"><SectionCard title="متابعة اشتراكات العملاء" subtitle="الحالة القريبة من الانتهاء تظهر عندما يتبقى ثلاثة أيام أو أقل، أما المنتهية فتظهر عند تجاوز تاريخ الانتهاء.">{subscriptionsQuery.data?.length ? <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-right"><thead className="bg-[#f8fcfb] text-xs text-slate-500"><tr><th className="px-5 py-3">العميل</th><th className="px-5 py-3">الباقة</th><th className="px-5 py-3">البداية</th><th className="px-5 py-3">النهاية</th><th className="px-5 py-3">الحالة</th><th className="px-5 py-3">إجراء</th></tr></thead><tbody className="divide-y divide-[#edf3f1]">{subscriptionsQuery.data.map(subscription => { const status = statusLabels[subscription.displayStatus]; return <tr key={subscription.id} className="hover:bg-[#fbfefd]"><td className="px-5 py-4 font-extrabold text-[#083f4c]">{subscription.contactName}</td><td className="px-5 py-4"><p className="font-bold text-[#083f4c]">{subscription.packageName}</p>{subscription.packagePrice ? <p className="mt-1 text-xs text-slate-500">{money(subscription.packagePrice, subscription.packageCurrencyCode ?? "YER")}</p> : null}</td><td className="px-5 py-4 text-sm text-slate-500">{arabicDate(subscription.startDate)}</td><td className="px-5 py-4 text-sm text-slate-500">{arabicDate(subscription.endDate)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${status.className}`}>{status.label}</span></td><td className="px-5 py-4"><select value={subscription.status} onChange={event => updateStatus.mutate({ id: subscription.id, status: event.target.value as "active" | "expiring" | "expired" | "suspended" })} className="h-9 rounded-lg border border-[#dce8e5] bg-white px-2 text-xs font-bold text-[#0a6372]"><option value="active">تفعيل</option><option value="suspended">إيقاف</option><option value="expired">تأكيد انتهاء</option></select></td></tr>; })}</tbody></table></div> : <EmptyState title="لا توجد اشتراكات بعد" description="أضف باقة أولاً ثم اربطها بعميل لمتابعة تاريخ التجديد والانتهاء." />}</SectionCard></TabsContent>
      <TabsContent value="packages"><SectionCard title="باقات الإنترنت" subtitle="تُحفظ مدة الباقة وسعرها وعملتها. يمكنك إيقاف الباقة لاحقاً دون التأثير على الاشتراكات السابقة.">{packagesQuery.data?.length ? <div className="grid gap-4 p-5 sm:grid-cols-2 xl:grid-cols-3">{packagesQuery.data.map(item => <article key={item.id} className="rounded-2xl border border-[#dce8e5] bg-[#fbfdfc] p-4"><div className="flex items-start justify-between"><div><h3 className="font-extrabold text-[#083f4c]">{item.name}</h3><p className="mt-1 text-sm text-slate-500">{item.description || "دون وصف"}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.isActive ? "bg-[#eaf7f2] text-[#08735d]" : "bg-slate-100 text-slate-500"}`}>{item.isActive ? "نشطة" : "موقوفة"}</span></div><div className="mt-5 flex items-center justify-between border-t border-[#e3eeeb] pt-3"><span className="text-sm text-slate-500">{item.durationDays} يوم</span><b className="text-[#0a6372]">{money(item.price, item.currencyCode)}</b></div></article>)}</div> : <EmptyState title="لا توجد باقات بعد" description="أنشئ باقة شهرية أو أي مدة تناسب طريقة بيع الاشتراكات لديك." />}</SectionCard></TabsContent>
    </Tabs>
    <Dialog open={packageOpen} onOpenChange={setPackageOpen}><DialogContent dir="rtl"><DialogHeader><DialogTitle>إضافة باقة إنترنت</DialogTitle><DialogDescription>تستخدم هذه البيانات عند فتح اشتراك جديد للعميل.</DialogDescription></DialogHeader><form onSubmit={submitPackage} className="space-y-4 py-2"><Field label="اسم الباقة"><Input required value={packageForm.name} onChange={event => setPackageForm({ ...packageForm, name: event.target.value })} placeholder="مثال: باقة منزلية شهرية" /></Field><div className="grid gap-4 sm:grid-cols-3"><Field label="المدة بالأيام"><Input required inputMode="numeric" value={packageForm.durationDays} onChange={event => setPackageForm({ ...packageForm, durationDays: event.target.value })} /></Field><Field label="السعر"><Input required inputMode="decimal" value={packageForm.price} onChange={event => setPackageForm({ ...packageForm, price: event.target.value })} /></Field><Field label="العملة"><select value={packageForm.currencyCode} onChange={event => setPackageForm({ ...packageForm, currencyCode: event.target.value as PackageForm["currencyCode"] })} className="form-select"><option value="YER">ريال يمني</option><option value="SAR">ريال سعودي</option><option value="USD">دولار أمريكي</option></select></Field></div><Field label="وصف الباقة"><Textarea value={packageForm.description} onChange={event => setPackageForm({ ...packageForm, description: event.target.value })} placeholder="اختياري" /></Field><DialogFooter className="gap-2 sm:gap-0"><Button type="button" variant="outline" onClick={() => setPackageOpen(false)}>إلغاء</Button><Button type="submit" disabled={createPackage.isPending} className="bg-[#0a6372] hover:bg-[#084e5a]">حفظ الباقة</Button></DialogFooter></form></DialogContent></Dialog>
    <Dialog open={subscriptionOpen} onOpenChange={setSubscriptionOpen}><DialogContent dir="rtl"><DialogHeader><DialogTitle>اشتراك جديد</DialogTitle><DialogDescription>يحسب النظام تاريخ الانتهاء تلقائياً من مدة الباقة المحددة.</DialogDescription></DialogHeader><form onSubmit={submitSubscription} className="space-y-4 py-2"><Field label="العميل أو البقالة"><select required value={subscriptionForm.contactId} onChange={event => setSubscriptionForm({ ...subscriptionForm, contactId: event.target.value })} className="form-select"><option value="">اختر الحساب</option>{customerContacts.map(contact => <option key={contact.id} value={contact.id}>{contact.name}</option>)}</select></Field><Field label="الباقة"><select required value={subscriptionForm.packageId} onChange={event => setSubscriptionForm({ ...subscriptionForm, packageId: event.target.value })} className="form-select"><option value="">اختر الباقة</option>{activePackages.map(item => <option key={item.id} value={item.id}>{item.name} — {money(item.price, item.currencyCode)}</option>)}</select></Field><Field label="تاريخ البداية"><Input required type="date" value={subscriptionForm.startDate} onChange={event => setSubscriptionForm({ ...subscriptionForm, startDate: event.target.value })} /></Field><Field label="ملاحظات"><Textarea value={subscriptionForm.notes} onChange={event => setSubscriptionForm({ ...subscriptionForm, notes: event.target.value })} placeholder="اختياري" /></Field><DialogFooter className="gap-2 sm:gap-0"><Button type="button" variant="outline" onClick={() => setSubscriptionOpen(false)}>إلغاء</Button><Button type="submit" disabled={createSubscription.isPending} className="bg-[#0a6372] hover:bg-[#084e5a]">حفظ الاشتراك</Button></DialogFooter></form></DialogContent></Dialog>
  </div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label className="font-bold text-[#083f4c]">{label}</Label>{children}</div>; }
